name: testsandboxapisnap # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  testsandboxapisnap:
    command: usr/local/bin/testsandboxapi

parts:
  libportal:
    source: https://github.com/flatpak/libportal.git
    source-type: git
    source-branch: add-sandbox-check-api
    plugin: meson
    build-packages: [libglib2.0-dev-bin, pkg-config, cmake, libglib2.0-dev, libgtk-3-dev]
    meson-parameters:
    - -Dbackends=gtk3 -Dintrospection=false -Ddocs=false
    organize:
      "*.so": /lib/
    stage-packages:
    - libatk-bridge2.0-0
    - libatk1.0-0
    - libatspi2.0-0
    - libcairo-gobject2
    - libcairo2
    - libdatrie1
    - libepoxy0
    - libfontconfig1
    - libfreetype6
    - libfribidi0
    - libgdk-pixbuf2.0-0
    - libgraphite2-3
    - libgtk-3-0
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libpng16-16
    - libthai0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libx11-6
    - libxau6
    - libxcb-render0
    - libxcb-shm0
    - libxcb1
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxdmcp6
    - libxext6
    - libxfixes3
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1

  testsandboxapi:
    after: [libportal]
    source: https://github.com/mwleeds/testsandboxapi.git
    source-branch: master
    source-type: git
    plugin: meson
    build-packages: [gettext]
    stage-packages:
    - libatk-bridge2.0-0
    - libatk1.0-0
    - libatspi2.0-0
    - libcairo-gobject2
    - libcairo2
    - libdatrie1
    - libepoxy0
    - libfontconfig1
    - libfreetype6
    - libfribidi0
    - libgdk-pixbuf2.0-0
    - libgraphite2-3
    - libgtk-3-0
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libpng16-16
    - libthai0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libx11-6
    - libxau6
    - libxcb-render0
    - libxcb-shm0
    - libxcb1
    - libxcomposite1
    - libxcursor1
    - libxdamage1
    - libxdmcp6
    - libxext6
    - libxfixes3
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1